variables:
  # Needed if you want automatic submodule checkout
  # For details see https://docs.gitlab.com/ee/ci/yaml/README.html#git-submodule-strategy
  GIT_SUBMODULE_STRATEGY: recursive
  SKA_PYTHON_PYTANGO_BUILDER_IMAGE: artefact.skao.int/ska-tango-images-pytango-builder-alpine:9.3.30
  OCI_IMAGE_BUILD_CONTEXT: $(PWD)
  K8S_TEST_CLUSTER_TAG: k8srunner # k8srunner-psi-low

# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
image: $SKA_PYTHON_PYTANGO_BUILDER_IMAGE

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
cache:
  paths:
    - build

# The YAML file defines a set of jobs with constraints stating when they should be run.
# You can specify an unlimited number of jobs which are defined as top-level elements with an arbitrary name and always have to contain at least the script clause.
# In this case we have only the test job which produce an artifacts (it must be placed into a directory called "public")
# It is also specified that only the master branch will be subject of this job.

stages:
  - lint
  - build
  - join-reports
  - test
  - pages
  - publish
  - scan

clean shell runner:
  stage: .pre
  tags:
    - k8srunner
  script:
    # Gitlab CI badges creation
    - rm -rf build/*

python-lint:
  image: artefact.skao.int/ska-tango-images-pytango-builder-alpine:9.3.30
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile"; exit 1;)'
    - 'make help | grep python-lint'
    - 'echo "python-lint: updating pip3"; time pip3 install --upgrade pip'
    - 'echo "python-lint: installing tools"; time pip3 install poetry black isort pylint-junit'
    - poetry config virtualenvs.create false
    - poetry export --format requirements.txt --output requirements.txt --without-hashes --dev
    - time pip3 install -r requirements.txt;

#Join linting reports (This stage is temporary!)
join_linting_reports:
  stage: join-reports
  tags:
    - k8srunner
  script:
    - echo "This step is needed as the artifacts can't be passed in the same stage"
    - make join-lint-reports
  artifacts:
    paths:
      - build/
    when: always

copy-protobuf:
  image: registry.gitlab.com/ska-telescope/pst/ska-pst-common/ska-pst-common-proto:0.1.0-dev.c77e84f67
  stage: build
  tags:
    - k8srunner
  script:
    - echo "Copying files across to artifacts."
    - mkdir -p build/protobuf/ska_pst_lmc_proto
    - find /app/protobuf/ska/pst/lmc -iname "*.proto" -exec cp '{}' build/protobuf/ska_pst_lmc_proto \;
  artifacts:
    paths:
      - build/
    when: always

python-generate-code:
  allow_failure: false
  stage: build
  image: artefact.skao.int/ska-tango-images-pytango-builder-alpine:9.3.30
  needs:
    - copy-protobuf
  tags:
    - k8srunner
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-build'
    - 'echo "python-generate-code: updating pip3"; time pip3 install --upgrade pip'
    - poetry config virtualenvs.create false
  script:
    - make PROTOBUF_DIR="$(pwd)/build/protobuf" GENERATED_PATH="$(pwd)/generated" python-generate-code
  artifacts:
    paths:
      - generated/*

stop-k8s-test:
  image: "$SKA_K8S_TOOLS_DEPLOY_IMAGE"
  stage: test
  tags:
  - k8srunner
  when: manual
  variables:
    KUBE_NAMESPACE: ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
  script:
  - make k8s-uninstall-chart
  - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps
    --all
  - make k8s-delete-namespace
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    action: stop

k8s-test:
  # allow_failure: true
  image: $SKA_K8S_TOOLS_DEPLOY_IMAGE
  stage: test
  needs: ["oci-image-build"] # Required to pull oci from gitlab
  tags:
    - k8srunner
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA'
  before_script:
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - 'make help | grep k8s-test'
    - make k8s-install-chart
    - make k8s-vars
    - make k8s-wait
  script:
    - kubectl config get-contexts
    - make k8s-get-pods
    - make k8s-pod-versions
    - make k8s-describe
    - make k8s-test
    - make k8s-podlogs
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always
  environment:
    name: test/$CI_COMMIT_REF_SLUG
    on_stop: stop-k8s-test
    auto_stop_in: 1 minute
  rules:
    - exists:
        - tests/**/*

python-build-for-publication: # Executed on a tag
  allow_failure: false
  image: $SKA_K8S_TOOLS_DEPLOY_IMAGE
  needs:
    - python-generate-code
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-build'
    - 'echo "python-build-for-publication: updating pip3"; time pip3 install --upgrade pip'
    - pip3 install poetry black isort build
    - poetry config virtualenvs.create false

python-build-for-development: # Executed on non-tagged commit
  allow_failure: false
  stage: build
  needs:
    - python-generate-code
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-build'
    - 'echo "python-build-for-development: updating pip3"; time pip3 install --upgrade pip'
    - pip3 install poetry black isort build
    - poetry config virtualenvs.create false

python-test:
  # allow_failure: true
  image: artefact.skao.int/ska-tango-images-pytango-builder-alpine:9.3.30
  retry: 2
  tags:
    - k8srunner
  needs:
    - python-generate-code
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-test'
    - 'echo "python-test: updating pip3"; time pip3 install --upgrade pip'
    - poetry config virtualenvs.create false
    - poetry export --format requirements.txt --output requirements.txt --without-hashes --dev
    - time pip3 install -r requirements.txt
  script:
    - make python-test;

# Include CI templates
include:
  # Python packages build,lint, test and publish
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

  # OCI
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

  # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  # Create Gitlab CI badges from CI metrics
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # Create a release
  - project: 'ska-telescope/templates-repository'
    file : 'gitlab-ci/includes/release.gitlab-ci.yml'

  # Publish Helm chart
  - project: 'ska-telescope/templates-repository'
    file : 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

  # k8s steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

  # changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/changelog.gitlab-ci.yml'

  # Override for branch based builds
  - local: '.gitlab/ci/branch.yml'
    rules:
      - if: $CI_COMMIT_BRANCH =~ /at3.*/
