[tool.poetry]
name = "ska-pst-lmc"
version = "0.1.0"
description = "PST-LMC Tango device package"
authors = ["Team PST"]
license = "BSD-3-Clause"

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = "^3.7"
pytango = "^9.3.3"
ska-tango-base = "^0.13.0"
ska-ser-logging = "^0.4.1"
ska-telescope-model = "^1.3.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pylint = "^2.12.2"
pytest = "^7.1.0"
pytest-bdd = "^5.0.0"
pytest-cov = "^3.0.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pylint-junit = "^0.3.2"
coverage = "^6.3.2"
pytest-json-report = "^1.5.0"
pytest-mock = "^3.7.0"
mock = "^4.0.3"
Sphinx = "^4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
