apiVersion: v2
name: ska-pst-lmc-test-parent
description: A Helm parent chart for the Tango Example
type: application
version: 0.1.10
appVersion: 0.1.10
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-util
  version: 0.3.23
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-base
  version: 0.3.25
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-taranta
  version: 1.0.29
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-taranta.enabled
- name: ska-taranta-auth
  version: 0.1.5
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-taranta-auth.enabled
- name: ska-dashboard-repo
  version: 0.1.9
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-dashboard-repo.enabled
- name: ska-pst-lmc
  version: 0.2.4
  repository: file://../ska-pst-lmc
- name: ska-pst-smrb
  version: 0.1.1
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-pst-smrb.enabled
- name: ska-pst-recv
  version: 0.4.0
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-pst-recv.enabled
