# Default values for PST.LMC (ska-pst-lmc)
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true
image:
  registry: artefact.skao.int
  image: ska-pst-lmc
  tag: 0.6.5
  pullPolicy: IfNotPresent

system: SW-infrastructure
subsystem: ska-pst-lmc
telescope: SKA-low
subsystem_id: pst-low

labels:
  app: ska-pst-lmc
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
  - "--tries=10"
  - "--sleep=5"
  ports:
    recv:
      recv-mgmt:
        port:       8080
    smrb:
      smrb-mgmt:
        port:       8080
    dsp:
      dsp-mgmt:
        port:       8080

loggingLevel: 4 # This is INFO level

beam:
  simulationMode: 1
  monitor_polling_rate: 5000
  scanOutputDirPattern: /mnt/lfs/product/<eb_id>/<subsystem_id>/<scan_id>

smrb:
  simulationMode: 1
  monitor_polling_rate: 5000
  smrb_process_api_endpoint: ska-pst-smrb # these should come from pod name and port configs

recv:
  simulationMode: 1
  monitor_polling_rate: 5000
  recv_process_api_endpoint: ska-pst-recv # these should come from pod name and port configs

dsp:
  simulationMode: 1
  monitor_polling_rate: 5000
  dsp_process_api_endpoint: ska-pst-dsp # these should come from pod name and port configs

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.5
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 150Mi
  requests:
    cpu: 50m
    memory: 50Mi

# Default ska-pst-lmc device server instances
deviceServers:
  # controller has only one instance
  low-pst-beam:
    legacy_compatibility: true
    instances: ["01"]
    file: "data/beam.yaml"

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

nodeSelector: {}

affinity: {}

tolerations: []
