# Default values for PST.LMC (ska-pst-lmc)
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-pst-lmc
telescope: SKA-low

labels:
  app: ska-pst-lmc
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.5
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 60m
    memory: 150Mi
  requests:
    cpu: 20m
    memory: 50Mi


# Default docker image - used by all of PST.LMC
ska_pst_lmc:
  enabled: true
  image:
    registry: artefact.skao.int
    image: ska-pst-lmc
    tag: 0.1.0
    pullPolicy: IfNotPresent


# Default ska-pst-lmc device server instances
deviceServers:
  # controller has only one instance
  simple:
    instances: ["simple-01"]
    file: "data/simple.yaml"

nodeSelector: {}

affinity: {}

tolerations: []
